name: frota_mobile
description: Frota Mobile - JBS/Seara

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  get_it: ^7.6.4
  dio: ^5.3.2
  shared_preferences: ^2.2.1
  flutter_dotenv: ^6.0.1
  google_fonts: ^6.2.1
  geolocator: 14.0.3
  geocoding: 5.0.0
  google_maps_flutter: 2.18.0
  flutter_map: 8.3.1
  latlong2: 0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/backgrounds/
    - assets/icons/
    - assets/images/corrida/
    - assets/images/passageiro/bottom_bar/
    - assets/images/passageiro/cards/
    - assets/images/passageiro/mapa_home.png
    - assets/images/passageiro/avatar_placeholder.png
    - .env